### ISSUE TITLE
Fatal error after installation

### ISSUE THREAD

**Issue by Igorgro** [Gittenburg/Attachments#1]
After installing this extension get the following error:
`Fatal error: Uncaught TypeError: Argument 4 passed to MediaWiki\Linker\LinkRenderer::makeKnownLink() must be of the type array, string given, called in /var/www/wiki.imserver2.igormahov.home/includes/Linker.php on line 114 and defined in /var/www/wiki.imserver2.igormahov.home/includes/linker/LinkRenderer.php:290 Stack trace: #0 /var/www/wiki.imserver2.igormahov.home/includes/Linker.php(114): MediaWiki\Linker\LinkRenderer->makeKnownLink(Object(Title), Object(HtmlArmor), Array, 'action=attach') #1 /var/www/wiki.imserver2.igormahov.home/includes/Linker.php(145): Linker::link(Object(Title), Object(Message), Array, 'action=attach', Array) #2 /var/www/wiki.imserver2.igormahov.home/extensions/Attachments/includes/Attachments.php(149): Linker::linkKnown(Object(Title), Object(Message), Array, 'action=attach') #3 /var/www/wiki.imserver2.igormahov.home/extensions/Attachments/includes/AttachmentsHooks.php(64): Attachments::makeList(Object(Title), Array, Array, Object(RequestContext)) #4 /var/www/wiki.imserver2.igormahov.home/includes in /var/www/wiki.imserver2.igormahov.home/includes/linker/LinkRenderer.php on line 290`

**Comment by Gittenburg** [comment]
What version of MediaWiki are you using?

**Comment by Igorgro** [comment]
The latest one: 1.34

**Comment by Gittenburg** [comment]
Thanks for reporting, should be fixed in master.
