### ISSUE TITLE
Not compatible with MediaWiki 1.38.1

### ISSUE THREAD

**Issue by leclou69** [Gittenburg/Attachments#15]
Hi,
I noticed that the actual version is no longer compatible with MediaWiki 1.38.1.
Seems to be line 64 in ./includes/Attachments.php
<code>return RepoGroup::singleton()->getLocalRepo()->findFiles($titles);</code>
As written [here](https://www.mediawiki.org/wiki/Manual:GlobalFunctions.php/de#wfFindFile()) this seems to be deprecated.
Substituded the line as follows:
<code>return MediaWikiServices::getInstance()->getRepoGroup()->findFiles($titles);</code>
Now it seems to work.
Not sure, if there are any other places with deprecated functions, so a review would be great.
Thanks in advance, Markus

**Comment by Gittenburg** [comment]
Thanks for the report! I can confirm that this fixes the error :)

Let me know if you encounter any other problems.
